#variable declaration
CC=gcc
CFLAGS=-c -Wall
#basically variables are referenced anywhere in the file 
#using $(VARIABLE NAME)
basefile=bruh
secondfile=monke


#target:dependancy
#	command


1:$(basefile)1.o $(secondfile)1.o #write all of ur dependancies
	$(CC) $(basefile)1.o $(secondfile)1.o -o $(basefile)1 

$(basefile)1.o:$(basefile)1.c
	$(CC) $(CFLAGS) $(basefile)1.c

$(secondfile)1.o:$(secondfile)1.c
	$(CC) $(CFLAGS) $(secondfile)1.c

clean:
	del (basefile)1 .exe



2:$(basefile)2.o $(secondfile)2.o #write all of ur dependancies
	$(CC) $(basefile)2.o $(secondfile)2.o -o $(basefile)2 

$(basefile)2.o:$(basefile)2.c
	$(CC) $(CFLAGS) $(basefile)2.c

$(secondfile)2.o:$(secondfile)2.c
	$(CC) $(CFLAGS) $(secondfile)2.c

clean:
	del (basefile)2 .exe



3:$(basefile)3.o $(secondfile)3.o #write all of ur dependancies
	$(CC) $(basefile)3.o $(secondfile)3.o -o $(basefile)3 

$(basefile)3.o:$(basefile)3.c
	$(CC) $(CFLAGS) $(basefile)3.c

$(secondfile)3.o:$(secondfile)3.c
	$(CC) $(CFLAGS) $(secondfile)3.c

clean:
	del (basefile)3 .exe



4:$(basefile)4.o $(secondfile)4.o #write all of ur dependancies
	$(CC) $(basefile)4.o $(secondfile)4.o -o $(basefile)4 


$(basefile)4.o:$(basefile)4.c
	$(CC) $(CFLAGS) $(basefile)4.c

$(secondfile)4.o:$(secondfile)4.c
	$(CC) $(CFLAGS) $(secondfile)4.c

clean:
	del (basefile)4 .exe



5:$(basefile)5.o $(secondfile)5.o #write all of ur dependancies
	$(CC) $(basefile)5.o $(secondfile)5.o -o $(basefile)5 

$(basefile)5.o:$(basefile)5.c
	$(CC) $(CFLAGS) $(basefile)5.c

$(secondfile)5.o:$(secondfile)5.c
	$(CC) $(CFLAGS) $(secondfile)5.c

clean:
	del (basefile)5.exe